// $COMMENT#AGNOSTIC20#USE_SERVER_COMPONENTS#THATSAMODULE

// $COMMENT#AGNOSTIC20#USE_SERVER_LOGICS#IMPORTINGWITHEXTENSION
import serverLogics from "../../../../../imported/javascript/server.js";

// $COMMENT#AGNOSTIC20#USE_SERVER_LOGICS#IMPORTINGBYAFOLDER
import serverLogicsFolder from "../../../../../imported/javascript/server-js";

// $COMMENT#TESTS#VALID
// $COMMENT#AGNOSTIC20#USE_SERVER_COMPONENTS#USE_SERVER_LOGICS
