"use client";
// $COMMENT#AGNOSTIC20#USE_CLIENT_COMPONENTS#THATSAMODULE

// $COMMENT#AGNOSTIC20#USE_SERVER_LOGICS#IMPORTINGWITHEXTENSION
import serverLogics from "../../../../../imported/javascript/server.js";

// $COMMENT#AGNOSTIC20#USE_SERVER_LOGICS#IMPORTINGBYAFOLDER
import serverLogicsFolder from "../../../../../imported/javascript/server-js";

// $COMMENT#TESTS#INVALID
// $COMMENT#AGNOSTIC20#FORALIASVARIABLES#SERVERNEVERCLIENT
