export const testsComments = Object.freeze({
  thatsA: "That's a",
  thatsAn: "That's an",
  importingA: "...Importing a",
  withExtension: "with extension",
  withExtensionParentheses: "(with extension).",
  byFolder: "by a folder.",
  importing: "...Importing",
  viaStrategy: "via Special Agnostic Strategy",
  viaStrategyPeriod: "via Special Agnostic Strategy.",
  viaAlias: "Via alias.",
  viaBaseUrl: "Via baseUrl.",
  valid: "Valid.",
  invalid: "Invalid.",
});
