"use agnostic";
// $COMMENT#AGNOSTIC20#USE_AGNOSTIC_COMPONENTS#THATSAMODULE

// $COMMENT#AGNOSTIC20#USE_AGNOSTIC_LOGICS#IMPORTINGWITHEXTENSION
import agnosticLogics from "../../../../../imported/javascript/agnostic.js";

// $COMMENT#AGNOSTIC20#USE_AGNOSTIC_LOGICS#IMPORTINGBYAFOLDER
import agnosticLogicsFolder from "../../../../../imported/javascript/agnostic-js";

// $COMMENT#TESTS#VALID
// $COMMENT#AGNOSTIC20#USE_AGNOSTIC_COMPONENTS#USE_AGNOSTIC_LOGICS
