"use agnostic";
// $COMMENT#AGNOSTIC20#USE_AGNOSTIC_COMPONENTS#THATSAMODULE

// $COMMENT#AGNOSTIC20#USE_CLIENT_LOGICS#IMPORTINGWITHEXTENSION
import clientLogics from "../../../../../imported/javascript/client.js";

// $COMMENT#AGNOSTIC20#USE_CLIENT_LOGICS#IMPORTINGBYAFOLDER
import clientLogicsFolder from "../../../../../imported/javascript/client-js";

// $COMMENT#TESTS#INVALID
// $COMMENT#AGNOSTIC20#FORALIASVARIABLES#CLIENTLOGICSCANTBOTH
