"use client";
// $COMMENT#AGNOSTIC20#USE_CLIENT_COMPONENTS#THATSAMODULE

// $COMMENT#AGNOSTIC20#USE_AGNOSTIC_COMPONENTS#IMPORTINGWITHEXTENSION
import agnosticComponents from "../../../../../imported/javascript/agnostic.jsx";

// $COMMENT#AGNOSTIC20#USE_AGNOSTIC_COMPONENTS#IMPORTINGBYAFOLDER
import agnosticComponentsFolder from "../../../../../imported/javascript/agnostic-jsx";

// $COMMENT#TESTS#VALID
// $COMMENT#AGNOSTIC20#USE_CLIENT_COMPONENTS#USE_AGNOSTIC_COMPONENTS
