"use client";
// $COMMENT#AGNOSTIC20#USE_CLIENT_COMPONENTS#THATSAMODULE

// $COMMENT#AGNOSTIC20#USE_CLIENT_LOGICS#IMPORTINGWITHEXTENSION
import clientLogics from "../../../../../imported/javascript/client.js";

// $COMMENT#AGNOSTIC20#USE_CLIENT_LOGICS#IMPORTINGBYAFOLDER
import clientLogicsFolder from "../../../../../imported/javascript/client-js";

// $COMMENT#TESTS#VALID
// $COMMENT#AGNOSTIC20#USE_CLIENT_COMPONENTS#USE_CLIENT_LOGICS
